# Generated by Django 5.0.7 on 2024-07-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
