# Generated by Django 5.0.7 on 2024-07-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
